In [1]:
import pandas as pd

## Data Section 1 - Basics

In [3]:
# men teams
menteam = pd.read_csv("data/MTeams.csv")
menteam.head()

   TeamID     TeamName  FirstD1Season  LastD1Season
0    1101  Abilene Chr           2014          2026
1    1102    Air Force           1985          2026
2    1103        Akron           1985          2026
3    1104      Alabama           1985          2026
4    1105  Alabama A&M           2000          2026

In [4]:
mseason = pd.read_csv("data/MSeasons.csv")
mseason.head()

   Season     DayZero RegionW    RegionX    RegionY    RegionZ
0    1985  10/29/1984    East       West    Midwest  Southeast
1    1986  10/28/1985    East    Midwest  Southeast       West
2    1987  10/27/1986    East  Southeast    Midwest       West
3    1988  11/02/1987    East    Midwest  Southeast       West
4    1989  10/31/1988    East       West    Midwest  Southeast

In [5]:
# seeds
mseeds = pd.read_csv("data/MNCAATourneySeeds.csv")
mseeds.head()

   Season Seed  TeamID
0    1985  W01    1207
1    1985  W02    1210
2    1985  W03    1228
3    1985  W04    1260
4    1985  W05    1374

In [7]:
# cities 
cities = pd.read_csv("data/Cities.csv")
cities.head()

   CityID         City State
0    4001      Abilene    TX
1    4002        Akron    OH
2    4003       Albany    NY
3    4004  Albuquerque    NM
4    4005    Allentown    PA

In [8]:
# men regular season
mregularseason = pd.read_csv("data/MRegularSeasonCompactResults.csv")
mregularseason.head()

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985      20     1228      81     1328      64    N      0
1    1985      25     1106      77     1354      70    H      0
2    1985      25     1112      63     1223      56    H      0
3    1985      25     1165      70     1432      54    H      0
4    1985      25     1192      86     1447      74    H      0

In [9]:
# tournament result
mtourresult = pd.read_csv("data/MNCAATourneyCompactResults.csv")
mtourresult.head()

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

In [10]:
# sample submission 
samplesub1 = pd.read_csv("data/SampleSubmissionStage1.csv")
samplesub1.head()

               ID  Pred
0  2022_1101_1102   0.5
1  2022_1101_1103   0.5
2  2022_1101_1104   0.5
3  2022_1101_1105   0.5
4  2022_1101_1106   0.5

In [12]:
samplesub2 = pd.read_csv("data/SampleSubmissionStage2.csv")
samplesub2.head()

               ID  Pred
0  2026_1101_1102   0.5
1  2026_1101_1103   0.5
2  2026_1101_1104   0.5
3  2026_1101_1105   0.5
4  2026_1101_1106   0.5

## Data Section 2 - Team Box Scores

In [13]:
# male regular season
maleregseason = pd.read_csv("data/MRegularSeasonDetailedResults.csv")
maleregseason.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14

In [15]:
maletourdetail = pd.read_csv("data/MNCAATourneyDetailedResults.csv")
maletourdetail.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,134,1421,92,1411,84,N,1,32,69,...,31,14,31,17,28,16,15,5,0,22
1,2003,136,1112,80,1436,51,N,0,31,66,...,16,7,7,8,26,12,17,10,3,15
2,2003,136,1113,84,1272,71,N,0,31,59,...,28,14,21,20,22,11,12,2,5,18
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,12,17,14,17,20,21,6,6,21
4,2003,136,1143,76,1301,74,N,1,27,64,...,21,15,20,10,26,16,14,5,8,19

## Data Section 3 - Geography

In [16]:
# cities 
teamcities = pd.read_csv("data/Cities.csv")
teamcities.head()

   CityID         City State
0    4001      Abilene    TX
1    4002        Akron    OH
2    4003       Albany    NY
3    4004  Albuquerque    NM
4    4005    Allentown    PA

In [17]:
gamecities = pd.read_csv("data/MGameCities.csv")
gamecities.head()

   Season  DayNum  WTeamID  LTeamID   CRType  CityID
0    2010       7     1143     1293  Regular    4027
1    2010       7     1314     1198  Regular    4061
2    2010       7     1326     1108  Regular    4080
3    2010       7     1393     1107  Regular    4340
4    2010       9     1143     1178  Regular    4027

## Data Section 4 - Public Rankings

In [2]:
import pandas as pd

In [3]:
mensrangking = pd.read_csv("data/MMasseyOrdinals.csv")
mensrangking.head()

   Season  RankingDayNum SystemName  TeamID  OrdinalRank
0    2003             35        SEL    1102          159
1    2003             35        SEL    1103          229
2    2003             35        SEL    1104           12
3    2003             35        SEL    1105          314
4    2003             35        SEL    1106          260

## Data Section 5 - Supplements
This section contains additional supporting information, including coaches, conference affiliations, alternative team name spellings, bracket structure, and game results for NIT and other postseason tournaments.

In [5]:
# coaches 
mteamcoaches = pd.read_csv("data/MTeamCoaches.csv")
mteamcoaches.tail(10)

       Season  TeamID  FirstDayNum  LastDayNum            CoachName
13888    2026    1472            0          93           john_tauer
13889    2026    1473            0          93        kyle_gerdeman
13890    2026    1474            0          93        grant_leonard
13891    2026    1475            0          93          stan_gouard
13892    2026    1476            0          93          chris_kraus
13893    2026    1477            0          93  jaret_von_rosenberg
13894    2026    1478            0          93        nate_champion
13895    2026    1479            0          93         gary_manchel
13896    2026    1480            0          93           dave_moore
13897    2026    1481            0          93         ted_hotaling