In [2]:
import pandas as pd
import sys

sys.path.append('../src/')
from match_utils import match

In [3]:
data = pd.read_csv("ncaa_2026_data.csv")

In [3]:
def find_matchup(team1, team2, df):
    """
    Find the row for the matchup between team1 and team2.
    Returns the row if found, else None.
    """
    # Try original order
    mask = (df['Team_A'] == team1) & (df['Team_B'] == team2)
    # If not found, try reversed order
    if not mask.any():
        mask = (df['Team_A'] == team2) & (df['Team_B'] == team1)
    
    result = df[mask]
    return result if not result.empty else None

# Example usage
matchup = find_matchup("Duke", "Siena", data)
print(matchup)

                   ID Team_A Team_B  Win_Prob_A
24420  2026_1181_1373   Duke  Siena    0.891925
90413  2026_3181_3373   Duke  Siena    0.967630

## Round 64

### Friday, March 20, 2026

In [21]:
match("Louisville", "South Florida", data)

                    ID      Team_A         Team_B  Win_Prob_A
43110   2026_1257_1378  Louisville  South Florida    0.701326
109029  2026_3257_3378  Louisville  South Florida    0.967630

In [23]:
match("Wisconsin", "High Point", data)

                    ID      Team_A     Team_B  Win_Prob_A
34275   2026_1219_1458  High Point  Wisconsin    0.287048
100231  2026_3219_3458  High Point  Wisconsin    0.770439

In [27]:
match("Siena", "Duke", data)

                   ID Team_A Team_B  Win_Prob_A
24420  2026_1181_1373   Duke  Siena    0.891925
90413  2026_3181_3373   Duke  Siena    0.967630

In [25]:
match("Vanderbilt", "McNeese St", data)

                    ID      Team_A      Team_B  Win_Prob_A
45882   2026_1270_1435  McNeese St  Vanderbilt    0.126994
111788  2026_3270_3435  McNeese St  Vanderbilt    0.025000

In [28]:
match("Michigan St", "N Dakota St", data)

                    ID       Team_A       Team_B  Win_Prob_A
47140   2026_1277_1295  Michigan St  N Dakota St    0.912620
113039  2026_3277_3295  Michigan St  N Dakota St    0.393707

In [29]:
match("Arkansas", "Hawaii", data)

                   ID    Team_A  Team_B  Win_Prob_A
5099   2026_1116_1218  Arkansas  Hawaii    0.912620
71500  2026_3116_3218  Arkansas  Hawaii    0.398667

In [30]:
match("North Carolina", "VCU", data)

                    ID          Team_A Team_B  Win_Prob_A
53503   2026_1314_1433  North Carolina    VCU    0.750554
119367  2026_3314_3433  North Carolina    VCU    0.967630

In [31]:
match("Michigan", "Howard", data)

                    ID  Team_A    Team_B  Win_Prob_A
35356   2026_1224_1276  Howard  Michigan    0.279905
101308  2026_3224_3276  Howard  Michigan    0.025000

In [32]:
match("BYU", "Texas", data)

                   ID Team_A Team_B  Win_Prob_A
12066  2026_1140_1400    BYU  Texas    0.722013
78427  2026_3140_3400    BYU  Texas    0.025000

In [13]:
match("St Mary's CA", "Texas A&M", data)

                    ID        Team_A     Team_B  Win_Prob_A
62347   2026_1388_1401  St Mary's CA  Texas A&M    0.574534
128140  2026_3388_3401  St Mary's CA  Texas A&M    0.025000

In [15]:
match("Illinois", "Penn", data)

                    ID    Team_A Team_B  Win_Prob_A
36398   2026_1228_1335  Illinois   Penn    0.891925
102346  2026_3228_3335  Illinois   Penn    0.967630

In [16]:
match("Georgia", "St Louis", data)

                   ID   Team_A    Team_B  Win_Prob_A
31885  2026_1208_1387  Georgia  St Louis    0.392505
97851  2026_3208_3387  Georgia  St Louis    0.967630

In [17]:
match("Houston", "Idaho", data)

                    ID   Team_A Team_B  Win_Prob_A
34806   2026_1222_1225  Houston  Idaho    0.891925
100760  2026_3222_3225  Houston  Idaho    0.306525

In [18]:
match("Gonzaga", "Kennesaw", data)

                   ID   Team_A    Team_B  Win_Prob_A
32530  2026_1211_1244  Gonzaga  Kennesaw    0.904304
98493  2026_3211_3244  Gonzaga  Kennesaw    0.967630

In [19]:
match("Kentucky", "Santa Clara", data)

                    ID    Team_A       Team_B  Win_Prob_A
40667   2026_1246_1365  Kentucky  Santa Clara    0.715361
106597  2026_3246_3365  Kentucky  Santa Clara    0.882813

In [20]:
match("Texas Tech", "Akron", data)

                   ID Team_A      Team_B  Win_Prob_A
1013   2026_1103_1403  Akron  Texas Tech    0.274973
67438  2026_3103_3403  Akron  Texas Tech    0.025000

### Saturday, March 21, 2026

In [11]:
match("Arizona", "LIU Brooklyn", data)

                   ID   Team_A        Team_B  Win_Prob_A
3729   2026_1112_1254  Arizona  LIU Brooklyn    0.891925
70138  2026_3112_3254  Arizona  LIU Brooklyn    0.967630

In [7]:
match("Virginia", "Wright St", data)

                    ID    Team_A     Team_B  Win_Prob_A
65588   2026_1438_1460  Virginia  Wright St     0.91262
131331  2026_3438_3460  Virginia  Wright St     0.96763

In [15]:
match("Iowa St", "Tennessee St", data)

                    ID   Team_A        Team_B  Win_Prob_A
38146   2026_1235_1398  Iowa St  Tennessee St    0.891925
104087  2026_3235_3398  Iowa St  Tennessee St    0.967630

In [16]:
match("Alabama", "Hofstra", data)

                   ID   Team_A   Team_B  Win_Prob_A
1196   2026_1104_1220  Alabama  Hofstra     0.91262
67619  2026_3104_3220  Alabama  Hofstra     0.96763

In [17]:
match("Villanova", "Utah St", data)

                    ID   Team_A     Team_B  Win_Prob_A
65211   2026_1429_1437  Utah St  Villanova      0.6041
130963  2026_3429_3437  Utah St  Villanova      0.0250

In [18]:
match("Tennessee", "Miami OH", data)

                    ID    Team_A     Team_B  Win_Prob_A
46845   2026_1275_1397  Miami OH  Tennessee    0.637048
112746  2026_3275_3397  Miami OH  Tennessee    0.025000

## Women

### Friday, March 20 (First Round/Round of 64)

In [19]:
match("Duke", "Col Charleston", data)

                   ID          Team_A Team_B  Win_Prob_A
17311  2026_1158_1181  Col Charleston   Duke    0.279905
83327  2026_3158_3181  Col Charleston   Duke    0.025000

In [20]:
match("TCU", "UC San Diego", data)

                    ID Team_A        Team_B  Win_Prob_A
63016   2026_1395_1471    TCU  UC San Diego    0.807298
128801  2026_3395_3471    TCU  UC San Diego    0.967630

In [31]:
match("Oregon", "Virginia Tech", data)

                    ID  Team_A         Team_B  Win_Prob_A
56093   2026_1332_1439  Oregon  Virginia Tech    0.135189
121940  2026_3332_3439  Oregon  Virginia Tech    0.759733

In [32]:
match("Baylor", "Nebraska", data)

                   ID  Team_A    Team_B  Win_Prob_A
7262   2026_1124_1304  Baylor  Nebraska    0.173082
73651  2026_3124_3304  Baylor  Nebraska    0.688519

In [34]:
match("Washington", "S Dakota St", data)

                    ID       Team_A      Team_B  Win_Prob_A
59137   2026_1355_1449  S Dakota St  Washington    0.279905
124960  2026_3355_3449  S Dakota St  Washington    0.124415

In [35]:
match("Maryland", "Murray St", data)

                    ID    Team_A     Team_B  Win_Prob_A
45338   2026_1268_1293  Maryland  Murray St    0.303547
111246  2026_3268_3293  Maryland  Murray St    0.774031

In [37]:
match("Mississippi", "Gonzaga", data)

                   ID   Team_A       Team_B  Win_Prob_A
32565  2026_1211_1279  Gonzaga  Mississippi     0.91262
98528  2026_3211_3279  Gonzaga  Mississippi     0.02500

In [38]:
match("Texas", "Missouri St", data)

                    ID       Team_A Team_B  Win_Prob_A
48396   2026_1283_1400  Missouri St  Texas    0.126994
114289  2026_3283_3400  Missouri St  Texas    0.025000

In [40]:
match("Michigan", "Holy Cross", data)

                    ID      Team_A    Team_B  Win_Prob_A
34606   2026_1221_1276  Holy Cross  Michigan    0.279905
100561  2026_3221_3276  Holy Cross  Michigan    0.025000

In [41]:
match("North Carolina", "W Illinois", data)

                    ID          Team_A      Team_B  Win_Prob_A
53512   2026_1314_1442  North Carolina  W Illinois    0.891925
119375  2026_3314_3442  North Carolina  W Illinois    0.948152

In [42]:
match("LSU", "Jacksonville", data)

                    ID        Team_A Team_B  Win_Prob_A
38956   2026_1239_1261  Jacksonville    LSU    0.279905
104893  2026_3239_3261  Jacksonville    LSU    0.025000

In [44]:
match("Minnesota", "WI Green Bay", data)

                    ID     Team_A        Team_B  Win_Prob_A
47486   2026_1278_1453  Minnesota  WI Green Bay     0.90275
113383  2026_3278_3453  Minnesota  WI Green Bay     0.97500

In [45]:
match("Michigan St", "Colorado St", data)

                   ID       Team_A       Team_B  Win_Prob_A
18338  2026_1161_1277  Colorado St  Michigan St    0.279905
84351  2026_3161_3277  Colorado St  Michigan St    0.025000

In [46]:
match("NC State", "Tennessee", data)

                    ID    Team_A     Team_B  Win_Prob_A
51470   2026_1301_1397  NC State  Tennessee    0.622943
117346  2026_3301_3397  NC State  Tennessee    0.129000

In [47]:
match("Texas Tech", "Villanova", data)

                    ID      Team_A     Team_B  Win_Prob_A
63612   2026_1403_1437  Texas Tech  Villanova    0.760555
129390  2026_3403_3437  Texas Tech  Villanova    0.454473

In [48]:
match("Oklahoma", "Idaho", data)

                    ID Team_A    Team_B  Win_Prob_A
35653   2026_1225_1328  Idaho  Oklahoma    0.161147
101604  2026_3225_3328  Idaho  Oklahoma    0.025000

In [33]:
match("Duke", "TCU", data)

                   ID Team_A Team_B  Win_Prob_A
24441  2026_1181_1395   Duke    TCU    0.912620
90434  2026_3181_3395   Duke    TCU    0.089089

In [72]:
match("F Dickinson", "Iowa", data)

                   ID       Team_A Team_B  Win_Prob_A
27409  2026_1192_1234  F Dickinson   Iowa    0.279905
93391  2026_3192_3234  F Dickinson   Iowa    0.025000

# Second Round

### Men

In [73]:
match("Duke", "TCU", data)

                   ID Team_A Team_B  Win_Prob_A
24441  2026_1181_1395   Duke    TCU    0.912620
90434  2026_3181_3395   Duke    TCU    0.089089

In [74]:
match("Kansas", "St John's", data)

                    ID  Team_A     Team_B  Win_Prob_A
39771   2026_1242_1385  Kansas  St John's    0.651215
105705  2026_3242_3385  Kansas  St John's    0.767031

In [75]:
match("Louisville", "Michigan St", data)

                    ID      Team_A       Team_B  Win_Prob_A
43013   2026_1257_1277  Louisville  Michigan St    0.366153
108932  2026_3257_3277  Louisville  Michigan St    0.489024

In [76]:
match("UCLA", "Connecticut", data)

                   ID       Team_A Team_B  Win_Prob_A
19090  2026_1163_1417  Connecticut   UCLA    0.823063
85101  2026_3163_3417  Connecticut   UCLA    0.436174

## west

In [77]:
match("Arizona", "Utah St", data)

                   ID   Team_A   Team_B  Win_Prob_A
3899   2026_1112_1429  Arizona  Utah St    0.839695
70308  2026_3112_3429  Arizona  Utah St    0.967630

In [78]:
match("High Point", "Arkansas", data)

                   ID    Team_A      Team_B  Win_Prob_A
5100   2026_1116_1219  Arkansas  High Point    0.912620
71501  2026_3116_3219  Arkansas  High Point    0.634055

In [79]:
match("Texas", "Gonzaga", data)

                   ID   Team_A Team_B  Win_Prob_A
32681  2026_1211_1400  Gonzaga  Texas    0.823184
98644  2026_3211_3400  Gonzaga  Texas    0.025000

In [92]:
match("Purdue", "Miami FL", data)

                    ID    Team_A  Team_B  Win_Prob_A
46597   2026_1274_1345  Miami FL  Purdue    0.161147
112499  2026_3274_3345  Miami FL  Purdue    0.341126

## SOUTH

In [80]:
match("Iowa", "Florida", data)

                   ID   Team_A Team_B  Win_Prob_A
28515  2026_1196_1234  Florida   Iowa    0.335859
94493  2026_3196_3234  Florida   Iowa    0.025000

In [85]:
match("Vanderbilt","Nebraska", data)

                    ID    Team_A      Team_B  Win_Prob_A
51850   2026_1304_1435  Nebraska  Vanderbilt    0.633744
117724  2026_3304_3435  Nebraska  Vanderbilt    0.076191

In [86]:
match("VCU", "Illinois", data)

                    ID    Team_A Team_B  Win_Prob_A
36493   2026_1228_1433  Illinois    VCU     0.91262
102441  2026_3228_3433  Illinois    VCU     0.96763

In [87]:
match("Texas A&M", "Houston", data)

                    ID   Team_A     Team_B  Win_Prob_A
34977   2026_1222_1401  Houston  Texas A&M    0.739451
100931  2026_3222_3401  Houston  Texas A&M    0.025000

## MIDWEST

In [88]:
match("Michigan", "St Louis", data)

                    ID    Team_A    Team_B  Win_Prob_A
47032   2026_1276_1387  Michigan  St Louis    0.805236
112932  2026_3276_3387  Michigan  St Louis    0.967630

In [89]:
match("Texas Tech", "Alabama", data)

                   ID   Team_A      Team_B  Win_Prob_A
1374   2026_1104_1403  Alabama  Texas Tech    0.661390
67797  2026_3104_3403  Alabama  Texas Tech    0.434636

In [90]:
match("Tennessee", "Virginia", data)

                    ID     Team_A    Team_B  Win_Prob_A
63148   2026_1397_1438  Tennessee  Virginia    0.581764
128932  2026_3397_3438  Tennessee  Virginia    0.852677

In [91]:
match("Kentucky", "Iowa St", data)

                    ID   Team_A    Team_B  Win_Prob_A
37999   2026_1235_1246  Iowa St  Kentucky    0.678987
103940  2026_3235_3246  Iowa St  Kentucky    0.736875

## WOMEN

### FORTH NORTH 1

In [93]:
match("North Carolina", "Maryland", data)

                    ID    Team_A          Team_B  Win_Prob_A
45358   2026_1268_1314  Maryland  North Carolina    0.238075
111266  2026_3268_3314  Maryland  North Carolina    0.640507

In [4]:
match("Connecticut", "Syracuse", data)

                   ID       Team_A    Team_B  Win_Prob_A
19066  2026_1163_1393  Connecticut  Syracuse    0.904304
85077  2026_3163_3393  Connecticut  Syracuse    0.967630

In [5]:
match("Notre Dame", "Ohio St", data)

                    ID      Team_A   Team_B  Win_Prob_A
54804   2026_1323_1326  Notre Dame  Ohio St    0.392505
120659  2026_3323_3326  Notre Dame  Ohio St    0.076191

In [6]:
match("Vanderbilt", "Illinois", data)

                    ID    Team_A      Team_B  Win_Prob_A
36495   2026_1228_1435  Illinois  Vanderbilt    0.514019
102443  2026_3228_3435  Illinois  Vanderbilt    0.025000

### SACRAMENTO 2

In [95]:
match("Mississippi", "Minnesota", data)

                    ID     Team_A       Team_B  Win_Prob_A
47320   2026_1278_1279  Minnesota  Mississippi    0.581764
113218  2026_3278_3279  Minnesota  Mississippi    0.619638

In [96]:
match("Baylor", "Duke", data)

                   ID  Team_A Team_B  Win_Prob_A
7143   2026_1124_1181  Baylor   Duke    0.173082
73532  2026_3124_3181  Baylor   Duke    0.786655

In [97]:
match("Texas Tech", "LSU", data)

                    ID Team_A      Team_B  Win_Prob_A
43988   2026_1261_1403    LSU  Texas Tech    0.274973
109903  2026_3261_3403    LSU  Texas Tech    0.713795

In [7]:
match("Oklahoma St", "UCLA", data)

                    ID       Team_A Team_B  Win_Prob_A
55637   2026_1329_1417  Oklahoma St   UCLA    0.491423
121487  2026_3329_3417  Oklahoma St   UCLA    0.025000

### FORTH WORTH 3

In [98]:
match("Oregon", "Texas", data)

                    ID  Team_A Team_B  Win_Prob_A
56055   2026_1332_1400  Oregon  Texas     0.11001
121902  2026_3332_3400  Oregon  Texas     0.02500

In [99]:
match("NC State", "Michigan", data)

                    ID    Team_A    Team_B  Win_Prob_A
46950   2026_1276_1301  Michigan  NC State    0.912620
112850  2026_3276_3301  Michigan  NC State    0.678397

In [8]:
match("Kentucky", "West Virginia", data)

                    ID    Team_A         Team_B  Win_Prob_A
40749   2026_1246_1452  Kentucky  West Virginia    0.760664
106678  2026_3246_3452  Kentucky  West Virginia    0.621526

In [10]:
match("Alabama", "Louisville", data)

                   ID   Team_A      Team_B  Win_Prob_A
1233   2026_1104_1257  Alabama  Louisville    0.411939
67656  2026_3104_3257  Alabama  Louisville    0.075297

### SACRAMENTO 4

In [100]:
match("Oklahoma", "Michigan St", data)

                    ID       Team_A    Team_B  Win_Prob_A
47171   2026_1277_1328  Michigan St  Oklahoma    0.912620
113070  2026_3277_3328  Michigan St  Oklahoma    0.222863

In [101]:
match("Washington", "TCU", data)

                    ID Team_A      Team_B  Win_Prob_A
62994   2026_1395_1449    TCU  Washington    0.433659
128779  2026_3395_3449    TCU  Washington    0.901748

In [11]:
match("Virginia", "Iowa", data)

                    ID Team_A    Team_B  Win_Prob_A
37947   2026_1234_1438   Iowa  Virginia    0.642108
103889  2026_3234_3438   Iowa  Virginia    0.885386

In [13]:
match("South Carolina", "USC", data)

                    ID          Team_A Team_B  Win_Prob_A
61326   2026_1376_1425  South Carolina    USC    0.196162
127130  2026_3376_3425  South Carolina    USC    0.686366